# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  vmImage: 'Ubuntu-16.04'

steps:
# Testing package is already on dev branch
#- task: PowerShell@2
#  displayName: 'Get testing pkg'
#  inputs:
#    targetType: inline
#    script: "wget https://raw.githubusercontent.com/dudeisbrendan03/RESTful-api/dev/package.json"

- task: NodeTool@0
  displayName: 'install node'
- task: NodeTool@0
  inputs:
    versionSpec: '8.15'
  
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

#- script: npm audit --json > audit.json & exit 0
#  displayName: 'NPM Security Audit'
  
- task: Npm@1
  displayName: 'npm test'
  inputs:
    command: custom
    customCommand: 'test'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-RESULTS.xml'
    testRunTitle: 'Test results for JavaScript'
  condition: succeededOrFailed()

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1

